services:
  # 1. The Backend (Web Service)
  - type: web
    name: TodoListApp
    runtime: node
    plan: free
    region: Oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 22.22.0
      # You can define your DB path here if your code uses process.env.DB_PATH
      - key: DB_PATH
        value: ./database.sqlite 

  # 2. The Frontend (Static Site)
  - type: web
    name: TodoListAppFrontend
    runtime: static
    plan: free
    # Note: If you use React, the build command is usually 'npm run build' 
    # and the publishPath is usually './build' or './dist'
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: TodoListApp
          property: host

# # 3. The Database (PostgreSQL)
# databases:
#   - name: my-app-db
#     plan: free
#     region: ohio